name: Testflight Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to Testflight
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Set version number
        run: ./.github/scripts/ios/set_version_number.sh

      - name: Decrypt secrets
        env:
          IOS_KEYS: ${{ secrets.IOS_KEYS }}
        run: ./.github/scripts/ios/decrypt_secrets.sh

      - name: Install node dependencies
        run: 'npm i'

      - name: Install ionic
        run : 'npm install -g @ionic/cli'

      # Orange
      - name: orange / Build capacitor app
        run: 'ionic cap sync ios'
        env:
          VUE_APP_OAUTH_CLIENT_ID: nyXOY94HtiiEgNCTaSJ8RSDjxXCc0kGJnPVBrPZi
          VUE_APP_OAUTH_CLIENT_SECRET: cZhCRsP1E2erEF6EJInRlWxBz6xu5ZiO2P5Fq5QUAZkYr99chWDmdWdZ2KDtUj8PuarEjyev9YoqR6NjUF6ZhAgu8YyMVZxna6pRbThLG0IyyleV6bkJgWYvIfJua2hR
          VUE_APP_DEBUG: false
          VUE_APP_BASE_URL: https://api.ta-zeitblick.de
          VUE_APP_BRANDING: orange

      - name: orange / Archive project
        timeout-minutes: 10
        env:
          TARGET: Orange
        run: ./.github/scripts/ios/archive_app.sh

      - name: orange / Export .ipa
        run: ./.github/scripts/ios/export_ipa.sh
        env:
          TARGET: Orange

      - name: orange / Publish app
        if: success()
        env:
          APPLEID_USERNAME: ${{ secrets.APPLEID_USERNAME }}
          APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
          PRODUCT: 'TA Zeitblick'
        run: ./.github/scripts/ios/publish_testflight.sh

      # Red
      - name: red / Build capacitor app
        run: 'ionic cap sync ios'
        env:
          VUE_APP_OAUTH_CLIENT_ID: nyXOY94HtiiEgNCTaSJ8RSDjxXCc0kGJnPVBrPZi
          VUE_APP_OAUTH_CLIENT_SECRET: cZhCRsP1E2erEF6EJInRlWxBz6xu5ZiO2P5Fq5QUAZkYr99chWDmdWdZ2KDtUj8PuarEjyev9YoqR6NjUF6ZhAgu8YyMVZxna6pRbThLG0IyyleV6bkJgWYvIfJua2hR
          VUE_APP_DEBUG: false
          VUE_APP_BASE_URL: https://api.zeitstrom.com
          VUE_APP_BRANDING: red

      - name: red / Archive project
        timeout-minutes: 10
        env:
          TARGET: Red
        run: ./.github/scripts/ios/archive_app.sh

      - name: red / Export .ipa
        run: ./.github/scripts/ios/export_ipa.sh
        env:
          TARGET: Red

      - name: red / Publish app
        if: success()
        env:
          APPLEID_USERNAME: ${{ secrets.APPLEID_USERNAME }}
          APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
          PRODUCT: 'Zeitstrom'
        run: ./.github/scripts/ios/publish_testflight.sh
